### ISSUE TITLE
After applying a filter the "Reset filter" button has disappeared

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#84]
When a custom filter is applied, there should always be the possibility to reset the filter. I think that has been in place at one point, but seems to be lost. Especially with "Quicksearch" and "Custom Filter" these possibility should be shown.

**Comment by dasistwas** [comment]
Also when search in custom filter does not return an entry, the filter settings disappear so that I can not even modify my search.

**Comment by michaelpollak** [comment]
I have been working on this and see it as a compound problem.
1) Quicksearch is not a filter, reset filter needs to take this into account.
2) "Reset filters" shows up on empty custom filter inputs, anything special to reproduce?
3) Customfilter is hidden when no entries are shown, I guess this is a mistake?

**Comment by michaelpollak** [comment]
Bugs 1 and 3 are solved, if you find time can you please look over it and confirm these are valid fixes. I don't fully understand why the customfilter form was hidden in the first place when no entries are available. 
I can't reproduce an instance when a customfilter shows no entries and no reset button is visible. Maybe you can point me to a setup that reproduces your experience? 
Thank you David.

**Comment by michaelpollak** [comment]
I assume this is fixed and bug 2 was just a fluke? Maybe closing this and opening a new issue makes more sense if it still prevails. Thanks.

**Comment by dasistwas** [comment]
OK, solved when no results are shown. Still a problem when I want to clear my filter, but will open another issue.
